"""
Loads the synthetic supply chain CSVs (generated by generate_synthetic_data.py)
into Snowflake via PUT + COPY INTO on an internal stage.

Usage:
    python load_to_snowflake.py --connection UU60334
"""
import argparse
import os

import snowflake.connector

TABLES = [
    ("suppliers.csv", "SUPPLIERS"),
    ("parts.csv", "PARTS"),
    ("plants.csv", "PLANTS"),
    ("customers.csv", "CUSTOMERS"),
    ("purchase_orders.csv", "PURCHASE_ORDERS"),
    ("po_lines.csv", "PO_LINES"),
    ("shipments.csv", "SHIPMENTS"),
]

DATABASE = "SC_DEMO"
SCHEMA = "RAW"
STAGE = "SC_DEMO.RAW.LOAD_STAGE"


def main(connection_name, data_dir):
    conn = snowflake.connector.connect(connection_name=connection_name)
    cur = conn.cursor()

    cur.execute(f"CREATE STAGE IF NOT EXISTS {STAGE}")
    cur.execute(f"USE DATABASE {DATABASE}")
    cur.execute(f"USE SCHEMA {SCHEMA}")

    for filename, table in TABLES:
        local_path = os.path.join(data_dir, filename).replace("\\", "/")
        print(f"Loading {filename} -> {table}")
        cur.execute(f"TRUNCATE TABLE IF EXISTS {table}")
        cur.execute(f"PUT 'file://{local_path}' @{STAGE} OVERWRITE = TRUE AUTO_COMPRESS = TRUE")
        cur.execute(f"""
            COPY INTO {table}
            FROM @{STAGE}/{filename}.gz
            FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 NULL_IF = (''))
            ON_ERROR = ABORT_STATEMENT
        """)
        cur.execute(f"SELECT COUNT(*) FROM {table}")
        count = cur.fetchone()[0]
        print(f"  -> {table} now has {count} rows")

    cur.close()
    conn.close()
    print("Load complete.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--connection", default="UU60334")
    parser.add_argument("--data-dir", default=os.path.join(os.path.dirname(__file__), "..", "data"))
    args = parser.parse_args()
    main(args.connection, args.data_dir)
